[[plugins]]
repo = 'Shougo/dein.vim'

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/bundles/plugins/ale_settings.vim'

# statusline plugin
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/ctrlp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-quickrun.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/bundles/plugins/nerdtree.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-better-whitespace.vim'

[[plugins]]
repo = 'neovim/node-host'
build = 'npm install'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-indent-guides.vim'

[[plugins]]
repo = 'jremmen/vim-ripgrep'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-ripgrep.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

# Vim に Language Server Protocol クライアント機能を導入して Rubyの補完機能を復活させた
# https://qiita.com/suketa/items/c368b3acd11403c23169
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = 'source ~/.config/nvim/bundles/plugins/LanguageClient-neovim.vim'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-nerdtree-tabs.vim'

# rubyで定義元メソッドへジャンプ ctags+vim-tags - 気軽に楽しくプログラムと遊ぶ
# http://tamata78.hatenablog.com/entry/2015/07/16/211555
[[plugins]]
repo = 'szw/vim-tags'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-tags.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-css3-syntax.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/scss-syntax.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/auto-ctags.vim'
