[[plugins]]
repo = 'Shougo/dein.vim'

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/bundles/plugins/ale_settings.vim'

# statusline plugin
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/ctrlp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-quickrun.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/bundles/plugins/nerdtree.vim'
