[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']

[[plugins]]
repo = 'iurifq/ctrlp-rails.vim'
on_ft = ['ruby']
depends = ['ctrlp.vim']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete-clang.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-go.vim'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']

[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'javascript.jsx']
build = './install.sh'
hook_add = 'source ~/.config/nvim/bundles/plugins/tigris.vim'

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = ['swift']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']
