[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'iurifq/ctrlp-rails.vim'
on_ft = ['ruby']
depends = ['ctrlp.vim']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete-clang.vim'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-go.vim'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
