[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete-clang.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-go.vim'
